pipeline {
    agent any

    stages {

        stage("cloning the repo") {
            steps {
                git branch: 'main',
                url: 'https://github.com/Bashitha267/goWave.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t bashitha267/vehicle-service ./product-service'
            }
        }

        stage('Stop Old Container') {
            steps {
                sh '''
                    docker stop vehicle-service || true
                    docker rm vehicle-service || true
                '''
            }
        }

        stage('Run Container') {
            steps {
                sh '''
                    docker rm -f vehicle-service || true

                    docker run -d -p 4000:4000 \
                    --name vehicle-service \
                    -e MONGO_URI="${MONGO_URI}" \
                    bashitha267/vehicle-service
                '''
            }
        }

        stage('Clean old Docker images') {
            steps {
                sh '''
                    docker image prune -f
                    docker container prune -f
                '''
            }
        }
    }

    post {
        success {
            echo "======== pipeline executed successfully ========"
        }
        failure {
            echo "======== pipeline execution failed ========"
        }
    }
}